/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Audio = string[];

export interface Configschema {
  obs: {
    enable: boolean;
    address: string;
    password?: string;
    names: {
      scenes: {
        intermission: string;
      };
      audioToMute: Audio;
      audioToUnmute: Audio;
    };
  };
}
